### ISSUE TITLE
Fix slave boots properties to reference correct boots

### ISSUE THREAD

**Issue by MinLL** [DeviousDevices/DDi#134] opened 2015-01-31 00:29 UTC
Slorm, on 30 Jan 2015 - 3:09 PM, said:
Last test on boots, added slave boots to inventory try to fit slave boots and restrictive boots appear on pc. Slave boots show as unfitted in inventory and if you try to fit them you get the message that you can't fit two of the same item.

Upshot of this is that you can't update from 2.8.3 to 2.9.0 without starting a new game or boots will be unusable.

Trying to clean a save game with DD already installed would be a major undertaking as all the dependant mods would have to be removed as well, so the outcome may not be satisfactory in any case.

I'm nearly finished building a new pc so will be starting a new game shortly, so I'm happy to experiment on this game (around 140 hours) trying to clean it if anyone thinks the effort is worthwhile.

Edit: I'll get a log to see if it shows what's happening

Edit2: Here's the log but it doesn't show much. I playeradditem set of slave boots, try to fit them and restrictive boots appear on pc but there's no entry in inventory for restrictive boots only unfitted slave boots. Try to fit slave boots a second time but can't as already wearing boots
attachicon.gifPapyrus.0.log

EDIT3: For completeness I rolled back to 2.8.3 and an older save and repeated the same test and get the unrendered restrictive boots instead of the slave boots. I have noticed this a few times before but had put it down to DCUR fitting the wrong item, so hopefully not a save game issue after all
2.9.0 shouldn't be savegame breaking. It sounds like the wrong properties are set on the slave boots in DDx.

**Comment by Slorm** [comment] 2015-01-31 00:40
The offending item is xx0138D9 it gets worn instead of the other boots for some reason and so blocks the other boots. If it's removed with player.removeitem xx0138D9 1 then the other boots in inventory will fit properly afterwards

**Comment by Coopervane** [comment] 2015-01-31 07:02
Can't reproduce, can't see anything wrong in the records. Please uninstall Dcur, untill Kimy releases the next version of it, that mod is breaking everything.

**Comment by Slorm** [comment] 2015-01-31 13:17
I've done some further testing, unfortunately the effect is baked into the current game even using a script cleaner after removing DCUR, I can roll back to an older version from the backup for testing though.

From memory this isn't a new issue and it started after one of the DCUR upgrades (can't remember which one) I just assumed at the time that the DCUR event was wrongly fitting the unrendered restraint boots otherwise I'd have looked into it more closely at the time. I was more concerned about the problems with the Dwemer Machine working incorrectly when called in v4.2 so never thought much more about the boots.

**Comment by Coopervane** [comment] 2015-01-31 15:40
Alright, closing the issue as a false alarm then since it's clearly a Dcur bug. Although due to the zad_DeviousBoot keyword messup, i think i'll need to this DDx version with a "New game strongly recommended!" warning :/

**Closed by Coopervane** 2015-01-31 15:40 UTC
Labels: expansion

**Comment by MinLL** [comment] 2015-01-31 18:25
The DDx version shouldn't hit any boots keyword related snags, due to the script we wrote to fix that issue.
